adlinabasuki/ootd

- Gemfile.lock
- app/assets/stylesheets/pages/_dress_me.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/outfits_controller.rb
- app/models/occasion.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/outfits/dress_me.html.erb
- config/routes.rb
- db/migrate/20230307065134_make_null_true_user_id_on_occasions.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/occasions_controller_test.rb
form, seed file and removed user_id as mandatory for occasions
**Everyone**
run rails db:migrate and rails db:seed
> Fixed a bit for the select occasion

- app/views/layouts/application.html.erb
- app/views/outfits/new.html.erb
i did next to nothing on this page :)
> bare bones outfits-new page

- .gitignore
- Gemfile.lock
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_new_outfit.scss
- app/controllers/outfits_controller.rb
- app/views/layouts/application.html.erb
- app/views/outfits/new.html.erb
- app/views/pages/home.html.erb
very basic outfits-new and landing page (no navbar on home page)
> very basic outfits-new and landing

- app/assets/stylesheets/components/_text.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/items/index.html.erb
- app/views/outfits/dress_me.html.erb
> Final fixes for dress_me

- app/views/items/new.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
minor changes to navbar links and items#new
> minor changes to navbar links and items#new

- app/controllers/outfits_controller.rb
- app/views/outfits/new.html.erb
randomized outfit can now be displayed on outfits#new
> outfits displayed

- app/controllers/affirmations_controller.rb
- app/controllers/items_controller.rb
- app/controllers/outfits_controller.rb
- app/models/outfit.rb
- app/views/affirmations/display.html.erb
- app/views/outfits/new.html.erb
- config/routes.rb
- db/seeds.rb
updates in:
- view#new outfit
- outfit-controler
- routes
- outfit.rb
- (probably more)
> Creating outfits, works

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- db/seeds.rb
added seeds and landing page clickable
> added seeds and landing page clickable

- config/environments/production.rb
- db/seeds.rb
destroying seeds in correct order now wooooooo
> destroying seeds and stuff

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/pages/_new_outfit.scss
- app/views/outfits/dress_me.html.erb
- app/views/outfits/new.html.erb
> changes to buttons

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_new_outfit.scss
- app/views/affirmations/display.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/outfits/dress_me.html.erb
- app/views/outfits/new.html.erb
revised UI for outfits#new page
> revised outfits#new

- app/assets/stylesheets/components/_buttons.scss
- config/environments/development.rb
> local tunnel

- app/controllers/outfits_controller.rb
- db/seeds.rb
> user-filter on dress_me works

- app/assets/stylesheets/pages/_dress_me.scss
- app/views/devise/passwords/new.html.erb
- app/views/outfits/dress_me.html.erb
removed add item button on dress_me; fixed btn-primary on "forgot password"
> small changes to buttons

- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/show.html.erb
delete item works now on items#show page
> delete item works now

- app/assets/stylesheets/pages/_item_edit.scss
- app/controllers/items_controller.rb
- app/views/items/edit.html.erb
edit items page works but it looks ugly ¯\ (ツ) /¯
> items#edit works

- app/views/devise/registrations/edit.html.erb
temporary logout button within app (not just in landing page)
> logout link on edit user page

- app/controllers/affirmations_controller.rb
- app/controllers/outfits_controller.rb
- app/models/outfit.rb
- db/seeds.rb
so it's more likely to get a accepted than a rejected outfit etc
> Added logic to outfits controller 

- Gemfile
- app/assets/stylesheets/pages/_dress_me.scss
- app/controllers/items_controller.rb
- app/controllers/outfits_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/weather_controller.js
- app/models/item.rb
- app/models/items_weather.rb
- app/views/items/new.html.erb
- app/views/outfits/dress_me.html.erb
- db/migrate/20230314084311_create_items_weathers.rb
- db/schema.rb
- test/models/items_weather_test.rb
in dress_me, items are now also filtered by weather
> weather feature added

- app/controllers/outfits_controller.rb
- db/schema.rb
and outfits#index now only show accepted outfits
> Unclear changes to schema, maybe because of migration

- app/views/items/edit.html.erb
weather field is now added to "edit item" page
> added weather to edit item
